/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface CInterface extends ethers.utils.Interface {
  functions: {
    "sender()": FunctionFragment;
    "setSender()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "sender", values?: undefined): string;
  encodeFunctionData(functionFragment: "setSender", values?: undefined): string;

  decodeFunctionResult(functionFragment: "sender", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setSender", data: BytesLike): Result;

  events: {};
}

export class C extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: CInterface;

  functions: {
    sender(overrides?: CallOverrides): Promise<[string]>;

    "sender()"(overrides?: CallOverrides): Promise<[string]>;

    setSender(overrides?: Overrides): Promise<ContractTransaction>;

    "setSender()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  sender(overrides?: CallOverrides): Promise<string>;

  "sender()"(overrides?: CallOverrides): Promise<string>;

  setSender(overrides?: Overrides): Promise<ContractTransaction>;

  "setSender()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    sender(overrides?: CallOverrides): Promise<string>;

    "sender()"(overrides?: CallOverrides): Promise<string>;

    setSender(overrides?: CallOverrides): Promise<void>;

    "setSender()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    sender(overrides?: CallOverrides): Promise<BigNumber>;

    "sender()"(overrides?: CallOverrides): Promise<BigNumber>;

    setSender(overrides?: Overrides): Promise<BigNumber>;

    "setSender()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    sender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "sender()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setSender(overrides?: Overrides): Promise<PopulatedTransaction>;

    "setSender()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
