/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { B } from "../B";

export class B__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<B> {
    return super.deploy(overrides || {}) as Promise<B>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): B {
    return super.attach(address) as B;
  }
  connect(signer: Signer): B__factory {
    return super.connect(signer) as B__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): B {
    return new Contract(address, _abi, signerOrProvider) as B;
  }
}

const _abi = [
  {
    inputs: [],
    name: "c",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "num",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "sender",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_c",
        type: "address",
      },
    ],
    name: "setSender",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_num",
        type: "uint256",
      },
    ],
    name: "setVars",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610234806100206000396000f3fe608060405234801561001057600080fd5b50600436106100675760003560e01c806367e404ce1161005057806367e404ce146100d5578063c3da42b81461011a578063ced32b0c1461013a57600080fd5b80634e70b1dc1461006c5780636466414b14610088575b600080fd5b61007560005481565b6040519081526020015b60405180910390f35b6100d36100963660046101e6565b600055600180547fffffffffffffffffffffffff000000000000000000000000000000000000000090811633179091556002805490911630179055565b005b6001546100f59073ffffffffffffffffffffffffffffffffffffffff1681565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200161007f565b6002546100f59073ffffffffffffffffffffffffffffffffffffffff1681565b6100d36101483660046101ab565b8073ffffffffffffffffffffffffffffffffffffffff166350c36a526040518163ffffffff1660e01b8152600401600060405180830381600087803b15801561019057600080fd5b505af11580156101a4573d6000803e3d6000fd5b5050505050565b6000602082840312156101bc578081fd5b813573ffffffffffffffffffffffffffffffffffffffff811681146101df578182fd5b9392505050565b6000602082840312156101f7578081fd5b503591905056fea26469706673582212209f8f1f795f238285c8c541dd5de6c01c6206db847c671c13d9641d1683dca28164736f6c63430008040033";
